env:
  browser: false
  es2020: true
extends:
  - airbnb
  - plugin:node/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  {
    semi: 'off',
    'no-console': 'off',
    'no-plusplus': 'off',
    'no-new': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    'import/extensions': 'off',
    'node/no-unsupported-features/es-syntax': 0,
    'lines-between-class-members': 0,
    'import/no-unresolved': 0,
    'func-names': 0,
    'node/no-missing-import': 0,
    'class-methods-use-this': 0,
    'import/prefer-default-export': 0,
    '@typescript-eslint/no-explicit-any': 0,
    '@typescript-eslint/explicit-module-boundary-types': 0,
    '@typescript-eslint/ban-ts-comment': 0,
    'radix': 0,
  }
